service: authorize
useDotenv: true
provider:
  name: openwhisk
  ignore_certs: true

functions:





  buy-paypal:
    handler: manage_access.buy_paypal
    parameters:
      token_pass: ${env:token_pass}
      return_url: ${env:return_url}
      cancel_url: ${env:cancel_url}
      paypal_client_id: ${env:paypal_client_id}
      paypal_client_secret: ${env:paypal_client_secret}
      frontend_url: ${env:frontend_url}
    events: 
      - http: POST /buy_paypal
    bind:
      - service:
          name: cloudantnosqldb
          instance: Cloudant-vm
  manage-access:
    handler: manage_access.manage_access
    annotations:
      web-export: true
    parameters:
      token_pass: ${env:token_pass}
      return_url: ${env:return_url}
      cancel_url: ${env:cancel_url}
      paypal_client_id: ${env:paypal_client_id}
      paypal_client_secret: ${env:paypal_client_secret}
      frontend_url: ${env:frontend_url}
    bind:
      - service:
          name: cloudantnosqldb
          instance: Cloudant-vm        
plugins:
  - serverless-openwhisk
  - serverless-dotenv-plugin
